import { CommandRegistry } from './commandRegistryBase.js';

export function registerDefaultCommands(reg) {
  const registry = reg
    .registerHeartbeat()
    .register("role_getroleinfo", { clientVersion: "2.21.2-fa918e1997301834-wx", inviteUid: 0, platform: "hortor", platformExt: "mix", scene: "" })
    .register("system_getdatabundlever", { isAudit: false })
    .register("system_buygold", { buyNum: 1 })
    .register("system_claimhangupreward")
    .register("system_signinreward")
    .register("system_mysharecallback", { isSkipShareCard: true, type: 2 })
    .register("system_custom", { key: "", value: 0 })
    .register("task_claimdailypoint", { taskId: 1 })
    .register("task_claimdailyreward", { rewardId: 0 })
    .register("task_claimweekreward", { rewardId: 0 })
    .register("friend_batch", { friendId: 0 })
    .register("hero_recruit", { byClub: false, recruitNumber: 1, recruitType: 3 })
    .register("item_openbox", { itemId: 2001, number: 10 })
    .register("item_batchclaimboxpointreward")
    .register("item_openpack")
    .register("rank_getserverrank")
    .register("arena_startarea")
    .register("fight_startlevel")
    .register("fight_getlevelbattledata")
    .register("fight_calcleveltime")
    .register("fight_level")
    .register("arena_getareatarget", { refresh: false })
    .register("arena_getarearank")
    .register("store_goodslist", { storeId: 1 })
    .register("store_buy", { goodsId: 1 })
    .register("store_purchase", { goodsId: 1 })
    .register("store_refresh", { storeId: 1 })
    .register("legion_getinfo")
    .register("legion_signin")
    .register("legion_getwarrank")
    .register("legionwar_getdetails")
    .register("legion_storebuygoods")
    .register("legion_kickout")
    .register("legion_applylist")
    .register("legion_approveapply")
    .register("legion_refuseapply")
    .register("legion_agree")
    .register("legion_ignore")
    .register("legion_research")
    .register("legion_resetresearch")
    .register("legion_getinfobyid")
    .register("legion_getarearank")
    .register("saltroad_getsaltroadwartotalrank")
    .register("legionwar_getgoldmonthwarrank")
    .register("legion_getopponent")
    .register("legion_getbattlefield")
    .register("legion_claimpayloadtask")
    .register("legion_claimpayloadtaskprogress")
    .register("saltroad_getwartype")
    .register("saltroad_getsaltroadwargrouprank")
    .register("league_getbattlefield")
    .register("league_getgroupopponent")
    .register("legion_signup")
    .register("mail_getlist", { category: [0, 4, 5], lastId: 0, size: 60 })
    .register("mail_claimallattachment", { category: 0 })
    .register("mail_getmtlinfo")
    .register("mail_getmtlshortinfo")
    .register("study_startgame")
    .register("study_answer")
    .register("study_claimreward", { rewardId: 1 })
    .register("fight_starttower")
    .register("fight_startboss")
    .register("fight_startlegionboss")
    .register("fight_startdungeon")
    .register("fight_startpvp")
    .register("evotower_getinfo")
    .register("evotower_fight")
    .register("evotower_getlegionjoinmembers")
    .register("evotower_readyfight")
    .register("evotower_claimreward")
    .register("mergebox_getinfo")
    .register("mergebox_claimfreeenergy")
    .register("mergebox_openbox")
    .register("mergebox_automergeitem", { actType: 1 })
    .register("mergebox_mergeitem", { actType: 1 })
    .register("mergebox_claimcostprogress", { actType: 1 })
    .register("mergebox_claimmergeprogress", { actType: 1 })
    .register("evotower_claimtask", { taskId: 1 })
    .register("bottlehelper_claim")
    .register("bottlehelper_start", { bottleType: -1 })
    .register("bottlehelper_stop", { bottleType: -1 })
    .register("legionmatch_rolesignup")
    .register("artifact_lottery", { lotteryNumber: 1, newFree: true, type: 1 })
    .register("artifact_exchange")
    .register("genie_sweep", { genieId: 1 })
    .register("genie_buysweep")
    .register("discount_claimreward", { discountId: 1 })
    .register("collection_claimfreereward")
    .register("card_claimreward", { cardId: 1 })
    .register("tower_getinfo")
    .register("tower_claimreward")
    .register("presetteam_getinfo")
    .register("presetteam_setteam")
    .register("presetteam_saveteam", { teamId: 1 })
    .register("role_gettargetteam")
    .register("hero_exchange")
    .register("hero_gointobattle")
    .register("hero_gobackbattle")
    .register("artifact_load")
    .register("artifact_unload")
    .register("lordweapon_changedefaultweapon")
    .register("hero_heroupgradelevel")
    .register("hero_heroupgradeorder")
    .register("hero_heroupgradestar")
    .register("book_upgrade")
    .register("book_claimpointreward")
    .register("rank_getroleinfo")
    .register("nightmare_getroleinfo")
    .register("dungeon_selecthero")
    .register("bosstower_gethelprank")
    .register("dungeon_buymerchant")
    .register("activity_get")
    .register("activity_recyclewarorderrewardclaim")
    .register("legion_getpayloadtask")
    .register("legion_getpayloadkillrecord")
    .register("legion_getpayloadbf")
    .register("legion_getpayloadrecord")
    .register("warguess_getrank")
    .register("warguess_startguess")
    .register("warguess_getguesscoinreward")
    .register("legion_payloadsignup")
    .register("collection_goodslist")
    .register("car_getrolecar")
    .register("car_detail", { carId: 0, withLog: true, chat: false })
    .register("car_refresh", { carId: 0 })
    .register("car_claim", { carId: 0 })
    .register("car_send", { carId: 0, helperId: 0, text: "" })
    .register("car_getmemberhelpingcnt")
    .register("car_getmemberrank")
    .register("car_research")
    .register("car_claimpartconsumereward")
    .register("legacy_getinfo")
    .register("legacy_claimhangup")
    .register("legacy_gift_getlist")
    .register("legacy_gift_send", { recipientId: 0, itemId: 0, quantity: 0 })
    .register("legacy_gift_received")
    .register("role_commitpassword", { password: "", passwordType: 1 })
    .register("legacy_sendgift", { itemCnt: 0, legacyUIds: [], targetId: 0 })
    .register("equipment_confirm", { heroId: 0, part: 0, quenchId: 0, quenches: {} })
    .register("equipment_quench", { heroId: 0, part: 0, quenchId: 0, quenches: {}, seed: 0, skipOrange: false })
    .register("equipment_updatequenchlock", { heroId: 0, part: 0, slot: 0, isLocked: false })
    .register("matchteam_getroleteaminfo")
    .register("bosstower_getinfo")
    .register("bosstower_startboss")
    .register("bosstower_startbox")
    .register("discount_getdiscountinfo")
    .register("towers_getinfo")
    .register("towers_start")
    .register("towers_fight")
    .register("system_sendchatmessage")
    .register("gacha_drawreward", { num: 1, isGroup: false })
    .register("pearl_replaceskill")
    .register("pearl_exchangeskill")
    .register("pearl_unloadskill")
    .register("hero_rebirth")
    .register("activity_buystoregoods", { activityId: 0, goodsIndex: 0, buyNum: 1 })
    .register("activity_claimrolluppack", { id: 17 })
    .register("pkroom_appoint")
    .register("charge_claimaddup", { id: 1 })
    .register("activity_claimredquenchreward")
    .register("evotower_claimlegiontask", { taskId: 1 })
    .register("evotower_claimlegionprivilege")
    .register("activity_battlepassrewardclaim", { battlePassId: 1003 })
    .register("activity_selectrewards", { rewardIndex: 5 })
    .register("activity_startactegame")
    .register("activity_actegamestageclaim");

  registry.commands.set("fight_startareaarena", (ack = 0, seq = 0, params = {}) => {
    if (params?.targetId === undefined || params?.targetId === null) {
      throw new Error("fight_startareaarena requires targetId in params");
    }
    const payload = { ...params };
    const body = registry.encoder?.bon?.encode ? registry.encoder.bon.encode(payload) : payload;
    return { cmd: "fight_startareaarena", ack, seq, time: Date.now(), body };
  });

  registry.commands.set("fight_startpvp", (ack = 0, seq = 0, params = {}) => {
    const payload = { ...params };
    const body = registry.encoder?.bon?.encode ? registry.encoder.bon.encode(payload) : payload;
    return { cmd: "fight_startpvp", ack, seq, time: Date.now(), body };
  });

  return registry;
}
